name: angstrom_editor_template
version: 1.0.0+1
description: "A template angstrom game."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.11.0-200.1.beta

dependencies:
  angstrom: ^0.2.8
  angstrom_editor: ^0.7.4
  backstreets_widgets: ^0.41.1
  cupertino_icons: ^1.0.8
  drift_sounds: ^0.0.1
  flutter:
    sdk: flutter
  flutter_audio_games: ^0.51.7
  flutter_soloud: ^3.4.8
  meta: ^1.17.0
  shared_preferences: ^2.5.4
  uuid: ^4.5.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  package_rename: ^1.10.1
package_rename_config:
  android:
    app_name: Angstrom Template
    package_name: angstrom_editor_template
    override_old_package: com.example.example
    lang: kotlin

  ios:
    app_name: Angstrom Template
    bundle_name: angstrom_editor_demo
    package_name: com.example.angstrom_editor_demo

  web:
    app_name: Angstrom Template
    description: A template game for angstrom_editor.

  linux:
    app_name: Angstrom Template
    package_name: com.example.angstrom_editor_template
    exe_name: template

  windows:
    app_name: Angstrom Template
    organization: example
    copyright_notice: Copyright ©️ forever Example Company. All rights reserved.
    exe_name: template

  macos:
    app_name: Angstrom Template
    package_name: com.example.angstrom_editor_demo
    copyright_notice: Copyright ©️ forever Example Company. All rights reserved.

flutter:
  uses-material-design: true
  assets:
    - assets/
    - rooms/
